openapi: 3.0.0
info:
  title: Api Docs
  version: 0.0.0
servers: 
  - url: http://localhost:3000/
paths:
  /user/{id}:
    get:
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  firstName:
                    type: string
                  lastName:
                    type: string
                  age:
                    type: integer